export type DemoCSV = {
  id: string;
  name: string;
  category: string;
  rows: Record<string, string>[];
};

export const demoCSVColumns = ["review_text", "rating", "date", "product_name", "user_id"];

export const demoCSVs: DemoCSV[] = [
  {
    id: "quickcommerce",
    name: "QuickCommerce Reviews",
    category: "Grocery delivery app",
    rows: [
      {
        review_text:
          "Delivery was fast and checkout was easy, but the rider map stopped updating near my building.",
        rating: "4",
        date: "2026-04-03",
        product_name: "QuickCommerce Demo",
        user_id: "QC-1001",
      },
      {
        review_text:
          "Refund was approved after a missing item, but I still cannot see when the money will come back.",
        rating: "2",
        date: "2026-04-04",
        product_name: "QuickCommerce Demo",
        user_id: "QC-1002",
      },
      {
        review_text: "Discounts are great and I use the app every week for snacks and milk.",
        rating: "5",
        date: "2026-04-05",
        product_name: "QuickCommerce Demo",
        user_id: "QC-1003",
      },
      {
        review_text: "The app crashed right after payment and I was scared the order charged twice.",
        rating: "2",
        date: "2026-04-06",
        product_name: "QuickCommerce Demo",
        user_id: "QC-1004",
      },
      {
        review_text: "Please show the rider on a real map. The ETA jumps from 6 minutes to 22 minutes.",
        rating: "3",
        date: "2026-04-07",
        product_name: "QuickCommerce Demo",
        user_id: "QC-1005",
      },
      {
        review_text: "Checkout is smooth and repeat orders save me a lot of time.",
        rating: "5",
        date: "2026-04-08",
        product_name: "QuickCommerce Demo",
        user_id: "QC-1006",
      },
      {
        review_text: "Customer support kept sending automated replies when my vegetables were missing.",
        rating: "1",
        date: "2026-04-09",
        product_name: "QuickCommerce Demo",
        user_id: "QC-1007",
      },
      {
        review_text: "The delivery was genuinely quick, but substitutions should ask me first.",
        rating: "4",
        date: "2026-04-10",
        product_name: "QuickCommerce Demo",
        user_id: "QC-1008",
      },
      {
        review_text: "I want a wishlist for monthly groceries and baby products.",
        rating: "4",
        date: "2026-04-11",
        product_name: "QuickCommerce Demo",
        user_id: "QC-1009",
      },
      {
        review_text: "Refund tracker is badly needed. I should not have to contact support three times.",
        rating: "2",
        date: "2026-04-12",
        product_name: "QuickCommerce Demo",
        user_id: "QC-1010",
      },
      {
        review_text: "Good prices, fast delivery, and saved address make it very convenient.",
        rating: "5",
        date: "2026-04-13",
        product_name: "QuickCommerce Demo",
        user_id: "QC-1011",
      },
      {
        review_text: "Payment failed twice during a sale and then my cart emptied.",
        rating: "2",
        date: "2026-04-14",
        product_name: "QuickCommerce Demo",
        user_id: "QC-1012",
      },
    ],
  },
  {
    id: "fintech",
    name: "Fintech App Reviews",
    category: "Consumer finance app",
    rows: [
      {
        review_text: "UPI transfer failed but the debit showed instantly. The reversal status is unclear.",
        rating: "2",
        date: "2026-03-02",
        product_name: "Fintech Demo",
        user_id: "FT-2001",
      },
      {
        review_text: "KYC verification has been pending for four days and support only says to wait.",
        rating: "1",
        date: "2026-03-03",
        product_name: "Fintech Demo",
        user_id: "FT-2002",
      },
      {
        review_text: "The spending insights are useful and the monthly category breakdown is easy to read.",
        rating: "5",
        date: "2026-03-04",
        product_name: "Fintech Demo",
        user_id: "FT-2003",
      },
      {
        review_text: "Bill payment reminders are reliable, but the cashback terms are confusing.",
        rating: "4",
        date: "2026-03-05",
        product_name: "Fintech Demo",
        user_id: "FT-2004",
      },
      {
        review_text: "App asks for face verification again and again even after successful login.",
        rating: "2",
        date: "2026-03-06",
        product_name: "Fintech Demo",
        user_id: "FT-2005",
      },
      {
        review_text: "Please add a clear timeline for failed transfer refunds and owner status.",
        rating: "2",
        date: "2026-03-07",
        product_name: "Fintech Demo",
        user_id: "FT-2006",
      },
      {
        review_text: "The card controls are excellent. Freezing and unfreezing the card is instant.",
        rating: "5",
        date: "2026-03-08",
        product_name: "Fintech Demo",
        user_id: "FT-2007",
      },
      {
        review_text: "Transaction search is slow when I filter by merchant for older months.",
        rating: "3",
        date: "2026-03-09",
        product_name: "Fintech Demo",
        user_id: "FT-2008",
      },
      {
        review_text: "Support closed my ticket without explaining why the wallet top-up failed.",
        rating: "1",
        date: "2026-03-10",
        product_name: "Fintech Demo",
        user_id: "FT-2009",
      },
      {
        review_text: "I like the clean home screen and account balance loads quickly.",
        rating: "5",
        date: "2026-03-11",
        product_name: "Fintech Demo",
        user_id: "FT-2010",
      },
      {
        review_text: "Need exportable statements with custom date ranges for tax filing.",
        rating: "4",
        date: "2026-03-12",
        product_name: "Fintech Demo",
        user_id: "FT-2011",
      },
      {
        review_text: "Login OTP arrives late during peak hours and the session expires before I enter it.",
        rating: "2",
        date: "2026-03-13",
        product_name: "Fintech Demo",
        user_id: "FT-2012",
      },
      {
        review_text: "Recurring payments setup is simple and the confirmation screen feels trustworthy.",
        rating: "5",
        date: "2026-03-14",
        product_name: "Fintech Demo",
        user_id: "FT-2013",
      },
      {
        review_text: "Rewards page shows offers that are already expired.",
        rating: "3",
        date: "2026-03-15",
        product_name: "Fintech Demo",
        user_id: "FT-2014",
      },
      {
        review_text: "Add a fraud alert explanation when a transaction is blocked.",
        rating: "3",
        date: "2026-03-16",
        product_name: "Fintech Demo",
        user_id: "FT-2015",
      },
    ],
  },
  {
    id: "food-delivery",
    name: "Food Delivery Reviews",
    category: "Restaurant delivery app",
    rows: [
      {
        review_text: "Food arrived cold and the app still showed the courier waiting at the restaurant.",
        rating: "2",
        date: "2026-02-10",
        product_name: "Food Delivery Demo",
        user_id: "FD-3001",
      },
      {
        review_text: "The reorder button is excellent for weekday lunch.",
        rating: "5",
        date: "2026-02-11",
        product_name: "Food Delivery Demo",
        user_id: "FD-3002",
      },
      {
        review_text: "Missing fries in my combo and refund was only a small coupon.",
        rating: "2",
        date: "2026-02-12",
        product_name: "Food Delivery Demo",
        user_id: "FD-3003",
      },
      {
        review_text: "Restaurant choices are strong in my area and filters make discovery easy.",
        rating: "5",
        date: "2026-02-13",
        product_name: "Food Delivery Demo",
        user_id: "FD-3004",
      },
      {
        review_text: "The delivery fee changed at checkout after I had already selected the restaurant.",
        rating: "3",
        date: "2026-02-14",
        product_name: "Food Delivery Demo",
        user_id: "FD-3005",
      },
      {
        review_text: "Please show if my order is batched with another delivery.",
        rating: "3",
        date: "2026-02-15",
        product_name: "Food Delivery Demo",
        user_id: "FD-3006",
      },
      {
        review_text: "Support chat was polite but took 25 minutes to answer during dinner rush.",
        rating: "2",
        date: "2026-02-16",
        product_name: "Food Delivery Demo",
        user_id: "FD-3007",
      },
      {
        review_text: "Live order status is useful when it works, especially the kitchen preparation stage.",
        rating: "4",
        date: "2026-02-17",
        product_name: "Food Delivery Demo",
        user_id: "FD-3008",
      },
      {
        review_text: "The app crashed when I tried to apply a promo code.",
        rating: "2",
        date: "2026-02-18",
        product_name: "Food Delivery Demo",
        user_id: "FD-3009",
      },
      {
        review_text: "Packaging notes should be visible to the restaurant before cooking starts.",
        rating: "4",
        date: "2026-02-19",
        product_name: "Food Delivery Demo",
        user_id: "FD-3010",
      },
      {
        review_text: "I love the late-night selection and saved addresses.",
        rating: "5",
        date: "2026-02-20",
        product_name: "Food Delivery Demo",
        user_id: "FD-3011",
      },
      {
        review_text: "Driver location froze for 15 minutes and my order was marked delivered early.",
        rating: "1",
        date: "2026-02-21",
        product_name: "Food Delivery Demo",
        user_id: "FD-3012",
      },
      {
        review_text: "Need better allergen filters across menus.",
        rating: "4",
        date: "2026-02-22",
        product_name: "Food Delivery Demo",
        user_id: "FD-3013",
      },
      {
        review_text: "The estimated arrival time was accurate today and the handoff was smooth.",
        rating: "5",
        date: "2026-02-23",
        product_name: "Food Delivery Demo",
        user_id: "FD-3014",
      },
      {
        review_text: "Refund recovery after a cancelled order still feels too slow.",
        rating: "2",
        date: "2026-02-24",
        product_name: "Food Delivery Demo",
        user_id: "FD-3015",
      },
    ],
  },
  {
    id: "edtech",
    name: "EdTech App Reviews",
    category: "Learning platform",
    rows: [
      {
        review_text: "Live class video buffers every few minutes even on stable Wi-Fi.",
        rating: "2",
        date: "2026-01-05",
        product_name: "EdTech Demo",
        user_id: "ED-4001",
      },
      {
        review_text: "Recorded lessons are clear and the chapter bookmarks help revision.",
        rating: "5",
        date: "2026-01-06",
        product_name: "EdTech Demo",
        user_id: "ED-4002",
      },
      {
        review_text: "Doubt resolution takes too long after live class ends.",
        rating: "2",
        date: "2026-01-07",
        product_name: "EdTech Demo",
        user_id: "ED-4003",
      },
      {
        review_text: "Mock tests feel close to the real exam and explanations are helpful.",
        rating: "5",
        date: "2026-01-08",
        product_name: "EdTech Demo",
        user_id: "ED-4004",
      },
      {
        review_text: "Please add offline downloads for lecture notes and practice sets.",
        rating: "4",
        date: "2026-01-09",
        product_name: "EdTech Demo",
        user_id: "ED-4005",
      },
      {
        review_text: "The app logs me out during quizzes and loses my answers.",
        rating: "1",
        date: "2026-01-10",
        product_name: "EdTech Demo",
        user_id: "ED-4006",
      },
      {
        review_text: "Teacher quality is excellent, especially for math shortcuts.",
        rating: "5",
        date: "2026-01-11",
        product_name: "EdTech Demo",
        user_id: "ED-4007",
      },
      {
        review_text: "Parent progress reports need weekly summaries, not only daily activity.",
        rating: "4",
        date: "2026-01-12",
        product_name: "EdTech Demo",
        user_id: "ED-4008",
      },
      {
        review_text: "Live chat questions get buried when the class has more than 500 students.",
        rating: "3",
        date: "2026-01-13",
        product_name: "EdTech Demo",
        user_id: "ED-4009",
      },
      {
        review_text: "The streak reminders keep me consistent without feeling spammy.",
        rating: "5",
        date: "2026-01-14",
        product_name: "EdTech Demo",
        user_id: "ED-4010",
      },
      {
        review_text: "Payment succeeded but my premium course did not unlock for two hours.",
        rating: "2",
        date: "2026-01-15",
        product_name: "EdTech Demo",
        user_id: "ED-4011",
      },
      {
        review_text: "Need better search inside recorded classes by topic and formula.",
        rating: "4",
        date: "2026-01-16",
        product_name: "EdTech Demo",
        user_id: "ED-4012",
      },
      {
        review_text: "Assignment upload failed twice and no draft was saved.",
        rating: "2",
        date: "2026-01-17",
        product_name: "EdTech Demo",
        user_id: "ED-4013",
      },
      {
        review_text: "Daily practice questions are well paced and explanations are concise.",
        rating: "5",
        date: "2026-01-18",
        product_name: "EdTech Demo",
        user_id: "ED-4014",
      },
      {
        review_text: "Add a reliability indicator before joining live classes.",
        rating: "3",
        date: "2026-01-19",
        product_name: "EdTech Demo",
        user_id: "ED-4015",
      },
    ],
  },
  {
    id: "ecommerce",
    name: "E-commerce Product Reviews",
    category: "Retail marketplace",
    rows: [
      {
        review_text: "The product photos looked premium, but the actual fabric felt much thinner.",
        rating: "2",
        date: "2026-05-01",
        product_name: "E-commerce Demo",
        user_id: "EC-5001",
      },
      {
        review_text: "Delivery was faster than promised and the packaging was neat.",
        rating: "5",
        date: "2026-05-02",
        product_name: "E-commerce Demo",
        user_id: "EC-5002",
      },
      {
        review_text: "Return pickup was rescheduled three times without a clear reason.",
        rating: "2",
        date: "2026-05-03",
        product_name: "E-commerce Demo",
        user_id: "EC-5003",
      },
      {
        review_text: "Size chart is inaccurate. I ordered medium and it fits like small.",
        rating: "2",
        date: "2026-05-04",
        product_name: "E-commerce Demo",
        user_id: "EC-5004",
      },
      {
        review_text: "Wishlist and price drop alerts helped me buy at the right time.",
        rating: "5",
        date: "2026-05-05",
        product_name: "E-commerce Demo",
        user_id: "EC-5005",
      },
      {
        review_text: "Customer photos in reviews were more useful than the brand images.",
        rating: "4",
        date: "2026-05-06",
        product_name: "E-commerce Demo",
        user_id: "EC-5006",
      },
      {
        review_text: "Exchange flow needs a clearer status page with pickup, inspection, and dispatch steps.",
        rating: "3",
        date: "2026-05-07",
        product_name: "E-commerce Demo",
        user_id: "EC-5007",
      },
      {
        review_text: "Received a damaged box and support asked for the same photos twice.",
        rating: "1",
        date: "2026-05-08",
        product_name: "E-commerce Demo",
        user_id: "EC-5008",
      },
      {
        review_text: "Search filters are powerful, especially material, color, and delivery date.",
        rating: "5",
        date: "2026-05-09",
        product_name: "E-commerce Demo",
        user_id: "EC-5009",
      },
      {
        review_text: "Please show seller reliability before checkout, not only after ordering.",
        rating: "4",
        date: "2026-05-10",
        product_name: "E-commerce Demo",
        user_id: "EC-5010",
      },
      {
        review_text: "The app froze when I tried to apply bank discount at payment.",
        rating: "2",
        date: "2026-05-11",
        product_name: "E-commerce Demo",
        user_id: "EC-5011",
      },
      {
        review_text: "The product comparison table saved me time.",
        rating: "5",
        date: "2026-05-12",
        product_name: "E-commerce Demo",
        user_id: "EC-5012",
      },
      {
        review_text: "Return refund took nine days and there was no expected settlement date.",
        rating: "2",
        date: "2026-05-13",
        product_name: "E-commerce Demo",
        user_id: "EC-5013",
      },
      {
        review_text: "Recommendations are repetitive after I buy one item.",
        rating: "3",
        date: "2026-05-14",
        product_name: "E-commerce Demo",
        user_id: "EC-5014",
      },
      {
        review_text: "I like the genuine review badges and verified buyer labels.",
        rating: "5",
        date: "2026-05-15",
        product_name: "E-commerce Demo",
        user_id: "EC-5015",
      },
      {
        review_text: "Add a fit predictor using my previous purchases.",
        rating: "4",
        date: "2026-05-16",
        product_name: "E-commerce Demo",
        user_id: "EC-5016",
      },
      {
        review_text: "Seller shipped the wrong color and replacement inventory was unavailable.",
        rating: "2",
        date: "2026-05-17",
        product_name: "E-commerce Demo",
        user_id: "EC-5017",
      },
      {
        review_text: "Checkout is quick with saved address and wallet balance.",
        rating: "5",
        date: "2026-05-18",
        product_name: "E-commerce Demo",
        user_id: "EC-5018",
      },
      {
        review_text: "Need a better alert when delivery address is outside serviceable area.",
        rating: "3",
        date: "2026-05-19",
        product_name: "E-commerce Demo",
        user_id: "EC-5019",
      },
      {
        review_text: "Product quality was excellent and matched the description exactly.",
        rating: "5",
        date: "2026-05-20",
        product_name: "E-commerce Demo",
        user_id: "EC-5020",
      },
    ],
  },
];
